### ISSUE TITLE
Infinite loop of same users when loading more

### ISSUE THREAD

**Issue by iamdarkle** [v17development/flarum-user-badges#18]
When clicking on a badge to see who has it, if we click on the "load more" button, it starts an infinite loop of the same users.

![9uWcmw6](https://user-images.githubusercontent.com/15818451/143472328-88e44d03-1d76-48d5-8923-b378d36c58eb.png)
_Image by @yuchangye who also reported this bug._

**Comment by jaspervriends** [comment]
I think this issue is related to this PR https://github.com/flarum/core/pull/3159 (which is already merged), but I am not too sure

**Comment by iamdarkle** [comment]
That makes a lot of sense (that some external change has affected it indirectly), I mean I just saw the last update of this extension was in June, I'm pretty sure this wasn't happening about 3 months ago when I added some styles to the badges pages.

**Comment by iamdarkle** [comment]
I have reviewed this and as you pointed out it was probably due to that issue, since this doesn't happen in the latest versions of Flarum, I'm closing 🙂
