### ISSUE TITLE
Error after click on "badge" page

### ISSUE THREAD

**Issue by justoverclockl** [v17development/flarum-user-badges#3]
After a click on "badge" page, this happen, and i cannot click on logo to come back to the homepage.

![Immagine 2021-03-15 120054](https://user-images.githubusercontent.com/79002016/111143884-a0833f80-8586-11eb-9470-526d2e038039.png)

Flarum core 0.1.0-beta.15
PHP version: 7.3.27
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2                                                                                                                              , calendar, ctype, curl, dba, dom, enchant, hash, fileinfo, filter, ftp, gd, get                                                                                                                              text, gmp, SPL, iconv, session, intl, json, mbstring, standard, mysqlnd, pcntl,                                                                                                                               mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readl                                                                                                                              ine, Reflection, imap, shmop, SimpleXML, soap, sockets, sodium, exif, sysvmsg, s                                                                                                                              ysvsem, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, memc                                                                                                                              ached, ionCube Loader, Zend OPcache
+------------------------------+------------------+--------+
| Flarum Extensions            |                  |        |
+------------------------------+------------------+--------+
| ID                           | Version          | Commit |
+------------------------------+------------------+--------+
| flarum-approval              | v0.1.0-beta.15   |        |
| flarum-bbcode                | v0.1.0-beta.15   |        |
| flarum-emoji                 | v0.1.0-beta.15   |        |
| flarum-lang-english          | v0.1.0-beta.15   |        |
| flarum-flags                 | v0.1.0-beta.15   |        |
| flarum-likes                 | v0.1.0-beta.15   |        |
| flarum-lock                  | v0.1.0-beta.15   |        |
| flarum-markdown              | v0.1.0-beta.15   |        |
| flarum-mentions              | v0.1.0-beta.15   |        |
| flarum-statistics            | v0.1.0-beta.15   |        |
| flarum-sticky                | v0.1.0-beta.15.1 |        |
| flarum-subscriptions         | v0.1.0-beta.15   |        |
| flarum-suspend               | v0.1.0-beta.15   |        |
| flarum-tags                  | v0.1.0-beta.15   |        |
| nearata-lang-italian         | v0.1.0-beta.15.1 |        |
| flarum-pusher                | v0.1.0-beta.15   |        |
| fof-best-answer              | 0.3.6            |        |
| fof-formatting               | 0.3.1            |        |
| fof-oauth                    | 0.2.1            |        |
| fof-analytics                | 0.11.0           |        |
| sycho-github-milestone       | v0.1.1           |        |
| fof-username-request         | 0.4.2            |        |
| fof-links                    | 0.5.4            |        |
| fof-share-social             | 0.3.0            |        |
| fof-polls                    | 0.3.2            |        |
| clarkwinkelmann-emojionearea | 0.3.0            |        |
| fof-socialprofile            | 0.2.3            |        |
| fof-user-bio                 | 0.4.2            |        |
| fof-linguist                 | 0.5.1            |        |
| phenomlab-fancybox-wrapper   | 0.5              |        |
+------------------------------+------------------+--------+
Base URL: https://flarum.it
Installation path: /home/customer/www/flarum.it/public_html
Debug mode: off

**Comment by Ralkage** [comment]
Any errors in your dev console when this issue occurs?

**Comment by justoverclockl** [comment]
> Any errors in your dev console when this issue occurs?

yes

![Immagine 2021-03-17 115201](https://user-images.githubusercontent.com/79002016/111456399-3d74e280-8717-11eb-9578-09f1018f4506.png)
