### ISSUE TITLE
Badges visible in user-card

### ISSUE THREAD

**Issue by jaspervriends** [v17development/flarum-user-badges#9]
Badges visible in user-card:

![](https://telegra.ph/file/1bbc28e7f62328a4a9f3d.png)

![](https://telegra.ph/file/068df2ddb1aa93add1dae.png)

**Comment by shebaoting** [comment]
This is great.

However, I would suggest hinting at the badge name as an alt, rather than displaying it directly.

**Comment by ramesh-dada** [comment]
I would like to suggest one more thing that when we click on badge from user card it should go to some url like /badges/1/#alphadot and it should highlight that user with css.
